name: VillagerOptimiser
main: com.froobworld.villageroptimiser.VillagerOptimiser
author: froobynooby
version: ${version}
api-version: 1.14
description: >
             Limits frequency of expensive pathfinding operations of villagers.
